# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_created=True)),
                ('nombre', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Urgente'), (4, 'Especial')], default=1)),
                ('estatus', models.IntegerField(choices=[(1, 'Incompleta'), (2, 'Completada'), (3, 'Espera')], default=1)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
    ]
